export const sustainabilityTopics = [
    "Renewable energy",
    "Climate change",
    "Sustainable agriculture",
    "Recycling",
    "Water conservation",
    "Air pollution",
    "Wildlife conservation",
    "Green transportation",
    "Energy efficiency",
    "Environmental policy",
    "Ocean conservation",
    "Eco-friendly products",
    "Waste management",
    "Biodiversity",
    "Deforestation",
    "Sustainable cities",
    "Green building",
    "Sustainable fashion",
    "Circular economy",
    "Clean energy",
    "Plastic pollution",
    "Composting",
    "Sustainable tourism",
    "Greenwashing",
    "Environmental education",
    "Ecosystem restoration",
    "Carbon footprint",
    "Sustainable development",
    "Pollution control",
    "Renewable resources",
    "Conservation biology",
    "Organic farming",
    "E-waste",
    "Water pollution",
    "Public transportation",
    "Sustainable packaging",
    "Renewable transportation",
    "Zero waste",
    "Land degradation",
    "Sustainable forestry",
    "Sustainable fishing",
    "Climate action",
    "Green energy",
    "Environmental justice",
    "Nature conservation",
    "Sustainable living",
    "Clean technology",
    "Renewable materials",
    "Green infrastructure",
    "Carbon neutrality",
    "Greenhouse gases",
    "Sustainable water management",
    "Endangered species",
    "Sustainable architecture",
    "Sustainable manufacturing",
    "Air quality",
    "Renewable power",
    "Environmental awareness",
    "Sustainable supply chain",
    "Water scarcity",
    "Pollution prevention",
    "Green jobs",
    "Sustainable waste disposal",
    "Renewable heating",
    "Sustainable transportation",
    "Climate resilience",
    "Urban sustainability",
    "Sustainable design",
    "Sustainable energy systems",
    "Energy conservation",
    "Climate adaptation",
    "Sustainable materials",
    "Renewable fuel",
    "Sustainable farming",
    "Greenhouse effect",
    "Eco-friendly technology",
    "Sustainable consumption",
    "Carbon emissions",
    "Sustainable urban planning",
    "Sustainable food systems",
    "Climate policy",
    "Natural resource conservation",
    "Ecological footprint",
    "Sustainable business",
    "Alternative energy",
    "Sustainable lifestyles",
    "Waste reduction",
    "Renewable electricity",
    "Green economy",
    "Eco-friendly practices",
    "Sustainable investing",
    "Sustainable forestry",
    "Environmental ethics",
    "Sustainable education",
    "Green initiatives",
    "Clean air",
    "Sustainable construction",
    "Renewable technologies",
    "Sustainable development goals",
    "Carbon offsets",
    "Sustainable water usage",
    "Sustainable tourism",
    "Ecotourism",
    "Sustainable landscaping",
    "Sustainable finance",
    "Climate justice",
    "Renewable heating",
    "Sustainable transportation",
    "Climate resilience",
    "Urban sustainability",
    "Sustainable design",
    "Sustainable energy systems",
    "Energy conservation",
    "Climate adaptation",
    "Sustainable materials",
    "Renewable fuel",
    "Sustainable farming",
    "Greenhouse effect",
    "Eco-friendly technology",
    "Sustainable consumption",
    "Carbon emissions",
    "Sustainable urban planning",
    "Sustainable food systems",
    "Climate policy",
    "Natural resource conservation",
    "Ecological footprint",
    "Sustainable business",
    "Alternative energy",
    "Sustainable lifestyles",
    "Waste reduction",
    "Renewable electricity",
    "Green economy",
    "Eco-friendly practices",
    "Sustainable investing",
    "Sustainable forestry",
    "Environmental ethics",
    "Sustainable education",
    "Green initiatives",
    "Clean air",
    "Sustainable construction",
    "Renewable technologies",
    "Sustainable development goals",
    "Carbon offsets",
    "Sustainable water usage",
    "Sustainable tourism",
    "Ecotourism",
    "Sustainable landscaping",
    "Sustainable finance",
    "Climate justice",
    "Sustainable mining",
    "Sustainable waste management",
    "Environmental conservation",
    "Sustainable healthcare",
    "Sustainable architecture",
    "Sustainable business practices",
    "Sustainable governance",
    "Sustainable water systems",
    "Sustainable development",
    "Sustainable energy policies",
    "Sustainable fashion industry",
    "Sustainable manufacturing processes",
    "Sustainable forestry practices",
    "Sustainable transportation systems",
    "Sustainable tourism practices",
    "Sustainable waste reduction",
    "Sustainable building materials",
    "Sustainable farming practices",
    "Sustainable consumer behavior",
    "Sustainable land use",
    "Sustainable resource management",
    "Sustainable infrastructure",
    "Sustainable education systems",
    "Sustainable finance and investments",
    "Sustainable food production",
    "Sustainable transportation fuels",
    "Sustainable supply chain management",
    "Sustainable waste disposal methods",
    "Sustainable water conservation",
    "Sustainable wildlife management",
    "Sustainable urban development",
    "Sustainable materials recycling",
    "Sustainable energy sources",
    "Sustainable fishing practices",
    "Sustainable waste recycling",
    "Sustainable technology innovation",
    "Sustainable waste treatment",
    "Sustainable water purification",
    "Sustainable environmental monitoring",
    "Sustainable disaster management",
    "Sustainable soil conservation",
    "Sustainable energy efficiency",
    "Sustainable community development",
    "Sustainable pollution control",
    "Sustainable consumer goods",
    "Sustainable environmental regulations",
    "Sustainable energy storage",
    "Sustainable waste recovery",
    "Sustainable water harvesting",
    "Sustainable wildlife conservation",
    "Sustainable urban transport",
    "Sustainable forest management",
    "Sustainable mining practices",
    "Sustainable water treatment",
    "Sustainable environmental impact assessment",
    "Sustainable biodiversity conservation",
    "Sustainable waste incineration",
    "Sustainable water desalination",
    "Sustainable land reclamation",
    "Sustainable energy generation",
    "Sustainable waste composting",
    "Sustainable water recycling",
    "Sustainable land restoration",
    "Sustainable energy distribution",
    "Sustainable waste minimization",
    "Sustainable water management systems",
    "Sustainable wildlife protection",
    "Sustainable urban planning and design",
    "Sustainable material sourcing",
    "Sustainable water infrastructure",
    "Sustainable coastal management",
    "Sustainable energy planning",
    "Sustainable waste segregation",
    "Sustainable water filtration",
    "Sustainable forest restoration",
    "Sustainable water resource planning",
    "Sustainable waste management solutions",
    "Sustainable water distribution",
    "Sustainable marine conservation",
    "Sustainable energy harvesting",
    "Sustainable waste treatment technologies",
    "Sustainable water conservation practices",
    "Sustainable waste recycling methods",
    "Sustainable water pollution control",
    "Sustainable energy systems integration",
    "Sustainable waste disposal practices",
    "Sustainable water quality monitoring",
    "Sustainable waste reduction strategies",
    "Sustainable water usage monitoring",
    "Sustainable waste management policies",
    "Sustainable water treatment technologies",
    "Sustainable energy infrastructure",
    "Sustainable waste recovery methods",
    "Sustainable water harvesting techniques",
    "Sustainable waste management processes",
    "Sustainable water purification methods",
    "Sustainable environmental monitoring systems",
    "Sustainable disaster management strategies",
    "Sustainable soil conservation methods",
    "Sustainable energy efficiency techniques",
    "Sustainable community development models",
    "Sustainable pollution control measures",
    "Sustainable consumer goods production",
    "Sustainable environmental regulations enforcement",
    "Sustainable energy storage solutions",
    "Sustainable waste recovery technologies",
    "Sustainable water harvesting systems",
    "Sustainable wildlife conservation methods",
    "Sustainable urban transport planning",
    "Sustainable forest management practices",
    "Sustainable mining techniques",
    "Sustainable water treatment processes",
    "Sustainable environmental impact assessment methods",
    "Sustainable biodiversity conservation strategies",
    "Sustainable waste incineration methods",
    "Sustainable water desalination techniques",
    "Sustainable land reclamation practices",
    "Sustainable energy generation technologies",
    "Sustainable waste composting methods",
    "Sustainable water recycling techniques",
    "Sustainable land restoration practices",
    "Sustainable energy distribution systems",
    "Sustainable waste minimization approaches",
    "Sustainable water management system design",
    "Sustainable wildlife protection methods",
    "Sustainable urban planning and design principles",
    "Sustainable material sourcing practices",
    "Sustainable water infrastructure development",
    "Sustainable coastal management strategies",
    "Sustainable energy planning models",
    "Sustainable waste segregation practices",
    "Sustainable water filtration techniques",
    "Sustainable forest restoration methods",
    "Sustainable water resource planning approaches",
    "Sustainable waste management solutions implementation",
    "Sustainable water distribution systems",
    "Sustainable marine conservation practices",
    "Sustainable energy harvesting methods",
    "Sustainable waste treatment technologies implementation",
    "Sustainable water conservation practices adoption",
    "Sustainable waste recycling methods utilization",
    "Sustainable water pollution control measures",
    "Sustainable energy systems integration techniques",
    "Sustainable waste disposal practices implementation",
    "Sustainable water quality monitoring systems",
    "Sustainable waste reduction strategies implementation",
    "Sustainable water usage monitoring techniques",
    "Sustainable waste management policies enforcement",
    "Sustainable water treatment technologies application",
    "Sustainable energy infrastructure development",
    "Sustainable waste recovery methods utilization",
    "Sustainable water harvesting techniques implementation",
    "Sustainable waste management processes establishment",
    "Sustainable water purification methods application",
    "Sustainable environmental monitoring systems utilization",
    "Sustainable disaster management strategies implementation",
    "Sustainable soil conservation methods adoption",
    "Sustainable energy efficiency techniques implementation",
    "Sustainable community development models implementation",
    "Sustainable pollution control measures implementation",
    "Sustainable consumer goods production practices",
    "Sustainable environmental regulations enforcement actions",
    "Sustainable energy storage solutions deployment",
    "Sustainable waste recovery technologies utilization",
    "Sustainable water harvesting systems implementation",
    "Sustainable wildlife conservation methods implementation",
    "Sustainable urban transport planning implementation",
    "Sustainable forest management practices application",
    "Sustainable mining techniques utilization",
    "Sustainable water treatment processes implementation",
    "Sustainable environmental impact assessment methods utilization",
    "Sustainable biodiversity conservation strategies implementation",
    "Sustainable waste incineration methods utilization",
    "Sustainable water desalination techniques implementation",
    "Sustainable land reclamation practices adoption",
    "Sustainable energy generation technologies deployment",
    "Sustainable waste composting methods utilization",
    "Sustainable water recycling techniques application",
    "Sustainable land restoration practices implementation",
    "Sustainable energy distribution systems establishment",
    "Sustainable waste minimization approaches adoption",
    "Sustainable water management system design implementation",
    "Sustainable wildlife protection methods utilization",
    "Sustainable urban planning and design principles application",
    "Sustainable material sourcing practices adoption",
    "Sustainable water infrastructure development implementation",
    "Sustainable coastal management strategies implementation",
    "Sustainable energy planning models application",
    "Sustainable waste segregation practices implementation",
    "Sustainable water filtration techniques application",
    "Sustainable forest restoration methods utilization",
    "Sustainable water resource planning approaches implementation",
    "Sustainable waste management solutions implementation",
    "Sustainable water distribution systems establishment",
    "Sustainable marine conservation practices adoption",
    "Sustainable energy harvesting methods utilization",
    "Sustainable waste treatment technologies implementation",
    "Sustainable water conservation practices adoption",
    "Sustainable waste recycling methods utilization",
    "Sustainable water pollution control measures implementation",
    "Sustainable energy systems integration techniques deployment",
    "Sustainable waste disposal practices implementation",
    "Sustainable water quality monitoring systems establishment",
    "Sustainable waste reduction strategies implementation",
    "Sustainable water usage monitoring techniques utilization",
    "Sustainable waste management policies enforcement actions",
    "Sustainable water treatment technologies application",
    "Sustainable energy infrastructure development implementation",
    "Sustainable waste recovery methods utilization",
    "Sustainable water harvesting techniques implementation",
    "Sustainable waste management processes establishment",
    "Sustainable water purification methods application",
    "Sustainable environmental monitoring systems utilization",
    "Sustainable disaster management strategies implementation",
    "Sustainable soil conservation methods adoption",
    "Sustainable energy efficiency techniques implementation",
    "Sustainable community development models implementation",
    "Sustainable pollution control measures implementation",
    "Sustainable consumer goods production practices",
    "Sustainable environmental regulations enforcement actions",
    "Sustainable energy storage solutions deployment",
    "Sustainable waste recovery technologies utilization",
    "Sustainable water harvesting systems implementation",
    "Sustainable wildlife conservation methods implementation",
    "Sustainable urban transport planning implementation",
    "Sustainable forest management practices application",
    "Sustainable mining techniques utilization",
    "Sustainable water treatment processes implementation",
    "Sustainable environmental impact assessment methods utilization",
    "Sustainable biodiversity conservation strategies implementation",
    "Sustainable waste incineration methods utilization",
    "Sustainable water desalination techniques implementation",
    "Sustainable land reclamation practices adoption",
    "Sustainable energy generation technologies deployment",
    "Sustainable waste composting methods utilization",
    "Sustainable water recycling techniques application",
    "Sustainable land restoration practices implementation",
    "Sustainable energy distribution systems establishment",
    "Sustainable waste minimization approaches adoption",
    "Sustainable water management system design implementation",
    "Sustainable wildlife protection methods utilization",
    "Sustainable urban planning and design principles application",
    "Sustainable material sourcing practices adoption",
    "Sustainable water infrastructure development implementation",
    "Sustainable coastal management strategies implementation",
    "Sustainable energy planning models application",
    "Sustainable waste segregation practices implementation",
    "Sustainable water filtration techniques application",
    "Sustainable forest restoration methods utilization",
    "Sustainable water resource planning approaches implementation",
    "Sustainable waste management solutions implementation",
    "Sustainable water distribution systems establishment",
    "Sustainable marine conservation practices adoption",
    "Sustainable energy harvesting methods utilization",
    "Sustainable waste treatment technologies implementation",
    "Sustainable water conservation practices adoption",
    "Sustainable waste recycling methods utilization",
    "Sustainable water pollution control measures implementation",
    "Sustainable energy systems integration techniques deployment",
    "Sustainable waste disposal practices implementation",
    "Sustainable water quality monitoring systems establishment",
    "Sustainable waste reduction strategies implementation",
    "Sustainable water usage monitoring techniques utilization",
    "Sustainable waste management policies enforcement actions",
    "Sustainable water treatment technologies application",
    "Sustainable energy infrastructure development implementation",
    "Sustainable waste recovery methods utilization",
    "Sustainable water harvesting techniques implementation",
    "Sustainable waste management processes establishment",
    "Sustainable water purification methods application",
    "Sustainable environmental monitoring systems utilization",
    "Sustainable disaster management strategies implementation",
    "Sustainable soil conservation methods adoption",
    "Sustainable energy efficiency techniques implementation",
    "Sustainable community development models implementation",
    "Sustainable pollution control measures implementation",
    "Sustainable consumer goods production practices",
    "Sustainable environmental regulations enforcement actions",
    "Sustainable energy storage solutions deployment",
    "Sustainable waste recovery technologies utilization",
    "Sustainable water harvesting systems implementation",
    "Sustainable wildlife conservation methods implementation",
    "Sustainable urban transport planning implementation",
    "Sustainable forest management practices application",
    "Sustainable mining techniques utilization",
    "Sustainable water treatment processes implementation",
    "Sustainable environmental impact assessment methods utilization",
    "Sustainable biodiversity conservation strategies implementation",
    "Sustainable waste incineration methods utilization",
    "Sustainable water desalination techniques implementation",
    "Sustainable land reclamation practices adoption",
    "Sustainable energy generation technologies deployment",
    "Sustainable waste composting methods utilization",
    "Sustainable water recycling techniques application",
    "Sustainable land restoration practices implementation",
    "Sustainable energy distribution systems establishment",
    "Sustainable waste minimization approaches adoption",
    "Sustainable water management system design implementation",
    "Sustainable wildlife protection methods utilization",
    "Sustainable urban planning and design principles application",
    "Sustainable material sourcing practices adoption",
    "Sustainable water infrastructure development implementation",
    "Sustainable coastal management strategies implementation",
    "Sustainable energy planning models application",
    "Sustainable waste segregation practices implementation",
    "Sustainable water filtration techniques application",
    "Sustainable forest restoration methods utilization",
    "Sustainable water resource planning approaches implementation",
    "Sustainable waste management solutions implementation",
    "Sustainable water distribution systems establishment",
    "Sustainable marine conservation practices adoption",
    "Sustainable energy harvesting methods utilization",
    "Sustainable waste treatment technologies implementation",
    "Sustainable water conservation practices adoption",
    "Sustainable waste recycling methods utilization",
    "Sustainable water pollution control measures implementation",
    "Sustainable energy systems integration techniques deployment",
    "Sustainable waste disposal practices implementation",
    "Sustainable water quality monitoring systems establishment",
    "Sustainable waste reduction strategies implementation",
    "Sustainable water usage monitoring techniques utilization",
    "Sustainable waste management policies enforcement actions",
    "Sustainable water treatment technologies application",
    "Sustainable energy infrastructure development implementation",
    "Sustainable waste recovery methods utilization",
    "Sustainable water harvesting techniques implementation",
    "Sustainable waste management processes establishment",
    "Sustainable water purification methods application",
    "Sustainable environmental monitoring systems utilization",
    "Sustainable disaster management strategies implementation",
    "Sustainable soil conservation methods adoption",
    "Sustainable energy efficiency techniques implementation",
    "Sustainable community development models implementation",
    "Sustainable pollution control measures implementation",
    "Sustainable consumer goods production practices",
    "Sustainable environmental regulations enforcement actions",
    "Sustainable energy storage solutions deployment",
    "Sustainable waste recovery technologies utilization",
    "Sustainable water harvesting systems implementation",
    "Sustainable wildlife conservation methods implementation",
    "Sustainable urban transport planning implementation",
    "Sustainable forest management practices application",
    "Sustainable mining techniques utilization",
    "Sustainable water treatment processes implementation",
    "Sustainable environmental impact assessment methods utilization",
    "Sustainable biodiversity conservation strategies implementation",
    "Sustainable waste incineration methods utilization",
    "Sustainable water desalination techniques implementation",
    "Sustainable land reclamation practices adoption",
    "Sustainable energy generation technologies deployment",
    "Sustainable waste composting methods utilization",
    "Sustainable water recycling techniques application",
    "Sustainable land restoration practices implementation",
    "Sustainable energy distribution systems establishment",
    "Sustainable waste minimization approaches adoption",
    "Sustainable water management system design implementation",
    "Sustainable wildlife protection methods utilization",
    "Sustainable urban planning and design principles application",
    "Sustainable material sourcing practices adoption",
    "Sustainable water infrastructure development implementation",
    "Sustainable coastal management strategies implementation",
    "Sustainable energy planning models application",
    "Sustainable waste segregation practices implementation",
    "Sustainable water filtration techniques application",
    "Sustainable forest restoration methods utilization",
    "Sustainable water resource planning approaches implementation",
    "Sustainable waste management solutions implementation",
    "Sustainable water distribution systems establishment",
    "Sustainable marine conservation practices adoption",
    "Sustainable energy harvesting methods utilization",
    "Sustainable waste treatment technologies implementation",
    "Sustainable water conservation practices adoption",
    "Sustainable waste recycling methods utilization",
    "Sustainable water pollution control measures implementation",
    "Sustainable energy systems integration techniques deployment",
    "Sustainable waste disposal practices implementation",
    "Sustainable water quality monitoring systems establishment",
    "Sustainable waste reduction strategies implementation",
    "Sustainable water usage monitoring techniques utilization",
    "Sustainable waste management policies enforcement actions",
    "Sustainable water treatment technologies application",
    "Sustainable energy infrastructure development implementation",
    "Sustainable waste recovery methods utilization",
    "Sustainable water harvesting techniques implementation",
    "Sustainable waste management processes establishment",
    "Sustainable water purification methods application",
    "Sustainable environmental monitoring systems utilization",
    "Sustainable disaster management strategies implementation",
    "Sustainable soil conservation methods adoption",
    "Sustainable energy efficiency techniques implementation",
    "Sustainable community development models implementation",
    "Sustainable pollution control measures implementation",
    "Sustainable consumer goods production practices",
    "Sustainable environmental regulations enforcement actions",
    "Sustainable energy storage solutions deployment",
    "Sustainable waste recovery technologies utilization",
    "Sustainable water harvesting systems implementation",
    "Sustainable wildlife conservation methods implementation",
    "Sustainable urban transport planning implementation",
    "Sustainable forest management practices application",
    "Sustainable mining techniques utilization",
    "Sustainable water treatment processes implementation",
    "Sustainable environmental impact assessment methods utilization",
    "Sustainable biodiversity conservation strategies implementation",
    "Sustainable waste incineration methods utilization",
    "Sustainable water desalination techniques implementation",
    "Sustainable land reclamation practices adoption",
    "Sustainable energy generation technologies deployment",
    "Sustainable waste composting methods utilization",
    "Sustainable water recycling techniques application",
    "Sustainable land restoration practices implementation",
    "Sustainable energy distribution systems establishment",
    "Sustainable waste minimization approaches adoption",
    "Sustainable water management system design implementation",
    "Sustainable wildlife protection methods utilization",
    "Sustainable urban planning and design principles application",
    "Sustainable material sourcing practices adoption",
    "Sustainable water infrastructure development implementation",
    "Sustainable coastal management strategies implementation",
    "Sustainable energy planning models application",
    "Sustainable waste segregation practices implementation",
    "Sustainable water filtration techniques application",
    "Sustainable forest restoration methods utilization",
    "Sustainable water resource planning approaches implementation",
    "Sustainable waste management solutions implementation"
]  